language:
  ruby

rvm:
  - '1.8'
  - '1.9'
  - '2.0'
  - '2.1'
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx

  fast_finish:
    true

install: bundle install --without debug

script: rake ci:all
