language:
  ruby

rvm:
  - '1.8'
  - '1.9'
  - '2.0'
  - '2.1'
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx

  fast_finish:
    true

install: bundle install --without debug

script: rake ci:all

deploy:
  provider: rubygems
  api_key:
    secure: Lqye2oKEatjnbc+aSPbYSp/zngJL4cUBaGZ6NlLqDajo7jMK71Sh52ZRCMvGIDZ11uH4lcPLTQKXZqUGh7s22nmZ61Zn71lWueaOvTOsdCffNTW4sHT8aLvfBXWJslWfsf4uBHSrDETuEaB0aZAVdpynrlkpID+PpaUAj3nxURc=
  on:
    tags: true
