language:
  ruby

rvm:
  - '1.8'
  - '1.9'
  - '2.0'
  - '2.1'
  - '2.3'
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: '1.8'
    - rvm: '1.9'
    - rvm: '2.0'
    - rvm: '2.1'
    - rvm: jruby-19mode
    - rvm: rbx

  fast_finish:
    true

install: bundle install --without debug

script: rake ci:all
