Rails.application.config.assets.precompile += %w( crud/application.css crud/application.js )
Rails.application.config.assets.precompile += %w( crud/flash_notices.css )
Rails.application.config.assets.precompile += %w( crud/dashboard.css crud/dashboard.js )
Rails.application.config.assets.precompile += %w( crud/pagination.css crud/pagination.js )
Rails.application.config.assets.precompile += %w( crud/search-icon.png )
